<a href="https://colab.research.google.com/github/TXXXW-WQ/Google-Colab-tutorial/blob/main/section_6/sklearn_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# scikit-learnの導入
機械学習ライブラリscikit-learnの使い方に慣れていきましょう。  
今回は、導入としてIrisの品種分類を行います。

## ● Iris dataset
Setosa、Versicolor、Versinicaの3つの品種について、以下をグラフ表示します。  
* Sepal length
* Sepal width
* Petal length
* Petal width

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

# Irisデータの読み込み
iris = datasets.load_iris()

# 各花のサイズ
iris_data = iris.data

# 散布図で表示
st_data = iris_data[:50]  # Setosa
vc_data = iris_data[50:100]  # Versicolor
vn_data = iris_data[100:150]  # Versinica

plt.scatter(st_data[:, 0], st_data[:, 1], label="Setosa")  # Sepal lengthとSepal width
plt.scatter(vc_data[:, 0], vc_data[:, 1], label="Versicolor")  # Sepal lengthとSepal width
plt.scatter(vn_data[:, 0], vn_data[:, 1], label="Versinica")  # Sepal lengthとSepal width
plt.legend()
plt.xlabel("Sepal length (cm)")
plt.ylabel("Sepal width (cm)")
plt.show()

plt.scatter(st_data[:, 2], st_data[:, 3], label="Setosa")  # Petal lengthとPetal width
plt.scatter(vc_data[:, 2], vc_data[:, 3], label="Versicolor")  # Petal lengthとPetal width
plt.scatter(vn_data[:, 2], vn_data[:, 3], label="Versinica")  # Petal lengthとPetal width
plt.legend()
plt.xlabel("Petal length (cm)")
plt.ylabel("Petal width (cm)")
plt.show()

## ● サポートベクターマシン
scikit-learnには様々な機械学習のアルゴリズムが含まれています。  
今回は、サポートベクターマシンという手法によりIrisの品種分類を行います。  
サポートベクターマシンのインスタンスを生成し、`fit`メソッドを実行するのみで分類を行うことが可能です。

In [ ]:
from sklearn import datasets
from sklearn import svm

iris = datasets.load_iris()
# print(iris.target)  # 品種を表すラベル 0:Setosa、1:Versicolor、2:Versinica

clf = svm.SVC()  # サポートベクターマシーン
clf.fit(iris.data, iris.target)  # 訓練

# 品種の判定 (Sepal length, Sepal width, Petal length, Petal width)
print(clf.predict([[5.1, 3.5, 1.4, 0.1], [6.5, 2.5, 4.4, 1.4], [5.9, 3.0, 6.2, 2.0]]))

In [4]:
# コード練習用
from sklearn import datasets
from sklearn import svm

iris = datasets.load_iris()
print(iris.data)
clf = svm.SVC()
clf.fit(iris.data, iris.target)

# print(clf.predict([[5.1, 3.5, 1.4, 0.1], [6.5, 2.5, 4.4, 1.4], [5.9, 3.0, 6.2, 2.0]]))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

SVC()